name: 'app'
type: 'nodejs:20'

web:
  locations:
    '/':
    # The folder in which your web application's HTML files and assets are stored
    root: ''
    # The front-controller pattern is commonly used in applications to provide a single point of entry for all requests.
    # For static sites, the index.html file often serves as the entry point.
    index: ['index.html']